# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a64916df8c8106706efa119689d66f30033fdec5200a1205ddfe6f9f00f833d06808d1a6b4a9e461d7c8a177570e6177568f3c07bf8e5baeeaa303cd8328db99

test:
  secret_key_base: 519c8d51847ffced04ad9cff8ba23d063b7c7172b76692c82986623547d845c922eb4ecc2e359cd5ac9eb58ba7d35921bfe454ad995dafba1129b9ef21755ace

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
